### ISSUE TITLE
Weapons, Effects, and buffs

### ISSUE THREAD

**Issue by MCarnegie** [cwoodard1121/zork#12]
we have to make a list of different weapons, effects, and buffs/debuffs that we want in the game so its easier for me to implement

make as many ideas as possible and later we can cut out ones we dont want

**Comment by cwoodard1121** [comment]
gonna keep this open

**Comment by cwoodard1121** [comment]
ITS DONE MARCO!!!! I ADDED WEAPONS AND STUFF!!!!!!!!!
