### ISSUE TITLE
For some reason the player has two inventories

### ISSUE THREAD

**Issue by MCarnegie** [cwoodard1121/zork#14]
in the debugger, i found one that was null and one that had stuff and its screwing with my code

**Comment by MCarnegie** [comment]
[Verse 1]
[Take a look inside your heart, is there any room for me?](https://genius.com/28421071/Pinkpantheress-boys-a-liar/Take-a-look-inside-your-heart-is-there-any-room-for-me)
[I won't have to hold my breath till you get down on one knee](https://genius.com/27418819/Pinkpantheress-boys-a-liar/I-wont-have-to-hold-my-breath-till-you-get-down-on-one-knee)
[Because you only want to hold me when I'm looking good enough](https://genius.com/28324386/Pinkpantheress-boys-a-liar/Because-you-only-want-to-hold-me-when-im-looking-good-enough)
Did you ever feel me? Would you ever picture us?
[Every time I pull my hair, well, it's only out of fear](https://genius.com/28324468/Pinkpantheress-boys-a-liar/Every-time-i-pull-my-hair-well-its-only-out-of-fear)
That you'll find me ugly and one day you'll disappear because

[Pre-Chorus]
What's the point of crying? It was never even love
Did you ever want me? Was I ever good enough?

[Chorus]
Thе, the boy's a liar, the boy's a liar
He doеsn't see ya, you're not looking at me, boy
The boy's a liar, the boy's a liar
He doesn't see ya, you're not looking at me, boy

[Post-Chorus]
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough

[Verse 2]
Baby, please, I just want to look nice for you
Come stay with me
Oh, you're not around, so what should I do?
I thought you liked the look about a girl just like me
Baby, please, I know you want to change me
Can you take a look inside your heart, is there any room for me?
[I won't have to hold my breath till you get down on one knee because](https://genius.com/27418819/Pinkpantheress-boys-a-liar/I-wont-have-to-hold-my-breath-till-you-get-down-on-one-knee)
You might also like
Boy’s a liar Pt. 2
PinkPantheress & Ice Spice
Did you know that there’s a tunnel under Ocean Blvd
Lana Del Rey
Love Language
SZA
[Pre-Chorus]
What's the point of crying? It was never even love
Did you ever want me? Was I ever good enough?

[Chorus]
The, the boy's a liar, the boy's a liar
He doesn't see ya, you're not looking at me, boy
The boy's a liar, the boy's a liar
He doesn't see ya, you're not looking at me, boy

[Post-Chorus]
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough
Good eno-o-ough, good eno-o-ough

**Comment by cwoodard1121** [comment]
ok i'll take a look

**Comment by cwoodard1121** [comment]
fixed it
